language: objective-c
cache: cocoapods
osx_image: xcode8.2

install:
- gem install xcov
- gem install slather

script:
- ./fastlane/travis.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
